### ISSUE TITLE
Does fuzzy matching work?

### ISSUE THREAD

**Issue by asad-awadia** [ozeidan/go-patricia#1]
Hey I am trying to get the fuzzy matching part working but it seems to not be giving me any results.

I have `123 456 7891` and `123 556 8891` in the Trie and I want the query of `123 656` to return me those two numbers but instead it returns nil.

Am I misunderstanding what fuzzy searching is here?

**Comment by asad-awadia** [comment]
@ozeidan

**Comment by ozeidan** [comment]
Hello. So I am not sure if this implementation adheres to the normal definition of fuzzy matching but my definition is: characters of the search term have to occur in the matching string in the same order, but not necessarily in one piece. So searching for `grch` will match `gosearch`, but `grhc` won't. 

I am not quite sure about the definition of fuzzy matching according to your examples. Should the query match those strings because all the characters in the query are also present in the strings?

**Comment by asad-awadia** [comment]
@ozeidan Fuzzy matching to me would be that the input query is 'close enough' to the strings in the tree

the 'edit distance' isn't too far out

If the trie has `123 456 7891` then search query `123 465 8971` should return the string - because it is fuzzily the same

but `567 123 6280` should not - cause its really far apart

Does that make sense?

**Comment by ozeidan** [comment]
Ah I see what you mean. So you are talking about something like the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance#:~:text=Informally%2C%20the%20Levenshtein%20distance%20between,considered%20this%20distance%20in%201965.)? 

So as of now the 'fuzzy' matching here works in a very different way (maybe we should call it something else then). I'll try to think about how we could implement the Levenshtein distance (or some similar heuristic). We'll have to find something that works well with the trie structure, as far as I remember the performance of the search depends on being able to eliminate a lot of branches of the trie very early on.
